spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/scottfrederick/config-server-multi-repo
          searchPaths: config-default
          repos:
            special:
              pattern: app2
              uri: https://github.com/scottfrederick/config-server-multi-repo
              searchPaths: config-app2
